id: AF5BF56F5
title: Lamenting Prayer to Jamyang Chökyi Lodrö
type: translation
pechas:
- I0A0AD712
- I004588B2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:16.562531
  last_modified_at: 2023-01-04 11:39:16.562538
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I0A0AD712/9493: '8076'
  I004588B2/BB60: '8076'
